---
sidebar: sidebar
permalink: beegfs-gens.html
keywords: BeeGFS, NetApp, solution
summary: "NetApp Verified Architectures combine the BeeGFS parallel file system with NetApp EF600 storage systems."
---

= BeeGFS on NetApp generations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
The BeeGFS on NetApp solution offers a first and second generation in its architecture.

Each generation incorporates a BeeGFS file system and an NetApp NVMe EF600 storage system. The second generation builds on the first to include these additional benefits:

* Double the performance and capacity while adding only 2U of rack space
* High availability (HA) based on a shared-disk, two-tier hardware design
* External qualification for NVIDIA’s DGX A100 SuperPOD

== Second generation
The second generation of BeeGFS on NetApp is optimized to meet the performance requirements of demanding workloads including high-performance computing (HPC) and HPC-style machine learning (ML), deep learning (DL) and similar artificial intelligence (AI) techniques. By incorporating a shared-disk high-availability (HA) architecture, the solution also meets the data durability and availability requirements of enterprises and other organizations that cannot afford downtime or data loss as they look for storage that can scale to keep up with their next generation workloads and use cases. This solution has not only been verified by NetApp, but it also passed external qualification as a storage option for the NVIDIA DGX SuperPOD.

For more information on the second generation, see link:beegfs-solution-overview.html[Second generation overview].


NOTE: This site focuses on the design and deployment for the _second_ generation. Information for future generations will be included as they are developed.

== First generation
The first generation of BeeGFS on NetApp was designed for machine learning (ML) and artificial intelligence (AI) workloads using NetApp EF600 NVMe storage systems, the BeeGFS parallel file system, NVIDIA DGX™ A100 systems, and NVIDIA® Mellanox® Quantum™ QM8700 200Gbps IB switches. This design also features 200Gbps InfiniBand (IB) for the storage and compute cluster interconnect fabric to provide customers with a completely IB-based architecture for high-performance workloads.

For complete details, see link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf[First Generation Design: NetApp EF-Series AI with NVIDIA DGX A100 Systems and BeeGFS].
