settings:
  name: "BeeGFS on NetApp with E-Series Storage"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: BeeGFS on NetApp docs
    url: "/index.html"
  - title: NetApp Validated Architectures
    entries:
    - title: About BeeGFS On NetApp
      url: beegfs-executive-summary.html
    - title: First generation NVA
      url: /beegfs-first-gen-overview.html
    - section: second-gen
  - title: Legal notices
    url: /legal-notices.html
