settings:
  name: "beegfs"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: BeeGFS solution docs
    url: "/index.html"
  - title: Get started
    entries:
      - title: Intro
        url:
      - title: Solution overview
        url:
      - title: Requirements
        url:
  - title: Design
    entries:
        - title: Overview
          url:
        - title: Architecture
          url:
        - title: Design
          url:
        - title: Validation
          url:
        - title: Performance tuning
          url:
  - title: Deploy
    entries:
        - title: Best practice
          url:
        - title: Hardware
          url:
        - title: Software
          url:
        - title: Validation
          url:
        - title: Performance tuning
          url:
  - title: Upgrade
    entries:
        - title: Overview
          url:
  - title: Troubleshoot
    entries:
        - title: Overview
          url:
