settings:
  name: "beegfs"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: BeeGFS docs
    url: "/index.html"
  - title: Get started
    entries:
      - title: Intro
        url: /beegfs-design-abstract.html
      - title: Executive summary
        url: /beegfs-design-executive-summary.html
      - title: Requirements
        url: /beegfs-design-technology-requirements.html
  - title: Design
    entries:
        - title: Overview
          url: /design/beegfs-design-solution-overview.html
        - title: Architecture
          url: /design/beegfs-design-solution-architecture.html
        - title: Validation
          url: /design/beegfs-design-solution-verification.html
        - title: Sizing guidelines
          url: /design/beegfs-design-solution-sizing-guidelines.html
        - title: Conclusion
          url: /design/beegfs-design-conclusion.html
  - title: Deploy
    entries:
        - title: Best practice
          url: /deploy/overview.html
        - title: Hardware
          url: /deploy/overview.html
        - title: Software
          url: /deploy/overview.html
        - title: Validation
          url: /deploy/overview.html
        - title: Performance tuning
          url: /deploy/overview.html
  - title: Upgrade
    entries:
        - title: Overview
          url: /upgrade/overview.html
  - title: Troubleshoot
    entries:
        - title: Overview
          url: /troubleshoot/overview.html
