settings:
  name: "BeeGFS on NetApp"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: BeeGFS on NetApp docs
    url: "/index.html"
  - title: NetApp Validated Architectures
    entries:
    - section: get-started
    - section: second-gen
  - title: Legal notices
    url: /legal-notices.html
