settings:
  name: "beegfs"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: BeeGFS docs
    url: "/index.html"
  - title: NetApp Validated Architectures
    entries:
    - section: get-started
    - section: second-gen
  - title: Legal notices
    url: /legal-notices.html
