---
sidebar: sidebar
permalink: second-gen/beegfs-solution-overview.html
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600
summary: "The BeeGFS on NetApp solution combines the BeeGFS parallel file system with NetApp EF600 storage systems for a reliable, scalable, and cost-effective infrastructure that keeps pace with demanding workloads."
---

= Solution overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
The BeeGFS on NetApp solution combines the BeeGFS parallel file system with NetApp EF600 storage systems for a reliable, scalable, and cost-effective infrastructure that keeps pace with demanding workloads.

== NVA program

The BeeGFS on NetApp solution is part of the NetApp Verified Architecture (NVA) program, which provides customers with reference configurations and sizing guidance for specific workloads and use cases. NVA solutions are thoroughly tested and designed to minimize deployment risks and to accelerate time to market.

== Design Overview

The BeeGFS on NetApp solution is designed as a scalable building block architecture, configurable for a variety of demanding workloads. Whether dealing with many small files, managing substantial large file operations, or a hybrid workload, the file system can be customized to meet these needs. High availability is built into the design with the use of a two-tier hardware structure that allows independent failover at multiple hardware layers and ensures consistent performance, even during partial system degradations. The BeeGFS file system enables a high-performance and scalable environment across different Linux distributions, and presents clients with a single easily accessible storage namespace. Learn more in the link:beegfs-architecture-overview.html[architecture overview].

== Use cases
The following use cases apply to the BeeGFS on NetApp solution:

* NVIDIA DGX SuperPOD systems featuring DGX’s with A100, H100, H200 and B200 GPU’s.
* Artificial Intelligence (AI) including machine learning (ML), deep learning (DL), large-scale natural language processing (NLP), and natural language understanding (NLU). For more information, see https://www.netapp.com/blog/beefs-for-ai-fact-vs-fiction/[BeeGFS for AI: Fact versus fiction^].
* High-performance computing (HPC) including applications accelerated by MPI (message passing interface) and other distributed computing techniques. For more information, see https://www.netapp.com/blog/beegfs-for-ai-ml-dl/[Why BeeGFS goes beyond HPC^].
* Application workloads characterized by:
** Reading or writing to files larger than 1GB
** Reading or writing to the same file by multiple clients (10s, 100s, and 1000s)
* Multi-terabyte or multi-petabyte datasets.
* Environments that need a single storage namespace optimizable for a mix of large and small files.

== Benefits
The key benefits of using BeeGFS on NetApp include:

* Availability of verified hardware designs providing full integration of hardware and software components to ensure predictable performance and reliability.
* Deployment and management using Ansible for simplicity and consistency at scale.
* Monitoring and observability provided using the E-Series Performance Analyzer and BeeGFS plugin. For more information, see https://www.netapp.com/blog/monitoring-netapp-eseries/[Introducing a Framework to Monitor NetApp E-Series Solutions^].
* High availability featuring a shared-disk architecture that provides data durability and availability.
* Support for modern workload management and orchestration using containers and Kubernetes. For more information, see https://www.netapp.com/blog/kubernetes-meet-beegfs/[Kubernetes meet BeeGFS: A tale of future-proof investment^].
