---
sidebar: sidebar
permalink: second-gen/beegfs-design-overview.html
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600
summary: "Specific equipment, cabling, and configurations are required to support the BeeGFS on NetApp solution, which combines the BeeGFS parallel file system with the NetApp EF600 storage systems."
---

= Design overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Specific equipment, cabling, and configurations are required to support the BeeGFS on NetApp solution, which combines the BeeGFS parallel file system with the NetApp EF600 storage systems.

Learn more:

* link:beegfs-design-hardware-architecture.html[Hardware configuration]
* link:beegfs-design-software-architecture.html[Software configuration]
* link:beegfs-design-solution-verification.html[Design verification]
* link:beegfs-design-solution-sizing-guidelines.html[Sizing guidelines]
* link:beegfs-design-performance-tuning.html[Performance tuning]

Derivative architectures with variations in design and performance:

* link:beegfs-design-high-capacity-building-block.html[High Capacity Building Block]
