---
sidebar: sidebar
permalink: beegfs-deploy-beegfs-on-netapp-using-ansible.html
keywords:
summary:
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To tell Ansible about the file and block nodes set up in previous sections, you need to build an inventory including hosts, groups, and variables the desired BeeGFS file system. Sample inventories can be downloaded from .

To actually apply the configuration described by this inventory,  use the various Ansible modules and roles provided in the NetApp E-Series Ansible collections, in particular the https://github.com/netappeseries/beegfs/tree/master/roles/beegfs_ha_7_2[BeeGFS HA 7.2 role^] that deploys the end-to-end solution.

While in- depth documentation is provided with the role, this deployment guide describes how to use it specifically to deploy a NetApp Verified Architecture using the second generation BeeGFS building block design.

[NOTE]
Although this section attempts to provide enough detail that prior experience with Ansible is not a prerequisite to deploy the solution, some familiarity with Ansible and related terminology is strongly recommended.

The building block architecture described by this NetApp Verified Architecture makes this process straightforward, outside of differing host names and management IPs, the only configuration options that change between each building block is whether it should run:

* BeeGFS management, metadata, and storage services.  The first building block deployed in each filesystem requires this configuration and is sometimes referred to as the base building block.
* BeeGFS Metadata and Storage services.
* BeeGFS Storage services.The use of these different configuration profiles for each building block allows the file system to flexibly scale to meet variable performance and capacity requirements using the same underlying hardware platforms and building block design.
