---
sidebar: sidebar
permalink: beegfs-deploy-hardware-deployment_overview.html
keywords:
summary:
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-02 10:33:57.179832
//

[.lead]
This section walks through the steps to physically assemble a single building block.  Unless otherwise noted,  these steps are identical for each building block in the cluster regardless of whether it  used to run BeeGFS metadata and storage services or storage services only. Each building block consists of two validated x86 file nodes directly connected using HDR (200Gb) InfiniBand to two NetApp block nodes.

[NOTE]
Because each building block includes two BeeGFS file nodes, a minimum of two building blocks is required to establish quorum in the failover cluster. While it is possible to configure a two-node cluster, there are limitations to this configuration that can prevent a successful failover to occur in some scenarios.  If a two-node cluster is required,  it is also possible to incorporate a third device as a tiebreaker,  though that is not covered in this deployment procedure.


