---
sidebar: sidebar
permalink: beegfs-gens.html
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600
summary: "The BeeGFS on NetApp solution is currently in its second generational design."
---

= Design generations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
The BeeGFS on NetApp solution is currently in its second generational design.

Both the first and second generation include a base architecture that incorporates a BeeGFS file system and an NVMe EF600 storage system. However, the second generation builds on the first to include these additional benefits:

* Double the performance and capacity while adding only 2U of rack space
* High availability (HA) based on a shared-disk, two-tier hardware design
* Architecture designed for NVIDIA DGX SuperPOD A100, H100, H200, and B200 systems, which was previously validated on a dedicated acceptance cluster at NVIDIA. Read more about NVIDIA DGX SuperPOD with NetApp in the link:https://docs.netapp.com/us-en/netapp-solutions/ai/ai-dgx-superpod.html[design guide].

== Second generational design

The second generation of BeeGFS on NetApp is optimized to meet the performance requirements of demanding workloads including high-performance computing (HPC), machine learning (ML), deep learning (DL), and other artificial intelligence (AI) techniques. By incorporating a shared-disk high-availability (HA) architecture, this design ensures data durability and availability, making it ideal for enterprises and other organizations that cannot afford downtime or data loss. The second generation design includes components such as PCIe gen5 servers and support for NVIDIA® Quantum™ QM9700 400Gb/s InfiniBand switches. This solution has not only been verified by NetApp but has also passed external qualification as a storage option for the NVIDIA DGX™ A100 SuperPOD, with extended certification for DGX SuperPOD H100, H200 and B200 systems.

== First generational design

The first generation of BeeGFS on NetApp was designed for machine learning (ML) and artificial intelligence (AI) workloads using NetApp EF600 NVMe storage systems, the BeeGFS parallel file system, NVIDIA DGX™ A100 systems, and NVIDIA® Mellanox® Quantum™ QM8700 200Gb/s IB switches. This design also features 200Gb/s InfiniBand (IB) for the storage and compute cluster interconnect fabric to provide a completely IB-based architecture for high-performance workloads.

For more information on the first generation, see link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf[NetApp EF-Series AI with NVIDIA DGX A100 Systems and BeeGFS^].
