---
sidebar: sidebar
permalink: beegfs-deploy-setting-up-an-ansible-control-node.html
keywords: Ansible control node, set up, EF600, NetApp, BeeGFS, Verified Architecture
summary: "Set up an Ansible control node."
---

= Set up an Ansible control node
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/



[.lead]
To set up an Ansible control node, you must identify a virtual or physical machine with network access to the management ports of all file and block nodes that can be used to configure the solution.

The following steps were tested on CentOS 8.4. For steps specific to your preferred Linux distribution, see the https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible documentation^].

. Install Python 3.9 and ensure the correct version of `pip` is installed.
+
....
sudo dnf install python3.9 -y
sudo dnf install python39-pip
sudo dnf install sshpass
....

. Create symbolic links, ensuring that the Python 3.9 binary is used whenever `python3` or `python` is called.
+
....
sudo ln -sf /usr/bin/python3.9 /usr/bin/python3
sudo ln -sf /usr/bin/python3 /usr/bin/python
....

.  Install the Python packages required by the NetApp BeeGFS collections.
+
....
python3 -m pip install ansible cryptography netaddr
....
+
[NOTE]
To ensure that you are installing a supported version of Ansible and all required Python packages, refer to the BeeGFS collection's Readme file. Supported versions are also noted in link:beegfs-technology-requirements.html[Technical requirements].

. Verify that the correct versions of Ansible and Python are installed.
+
....
ansible --version
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Mar 10 2021, 17:29:56) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
....

. Store the Ansible inventories used to describe the BeeGFS deployment in source control systems such as Git or BitBucket, and then install Git to interact with those systems.
+
....
sudo dnf install git -y
....

. Set up passwordless SSH. This is the easiest way to allow Ansible to access the remote BeeGFS file nodes from the Ansible control node.
+
.. On the Ansible control node, if needed, generate a pair of public keys using `ssh-keygen`

.. Set up passwordless SSH to each of the file nodes using `ssh-copy-id <ip_or_hostname>`
+
Do not set up passwordless SSH to the block nodes. This is neither supported nor required.

. Use Ansible Galaxy to install the version of the BeeGFS collection listed in link:beegfs-technology-requirements.html[Technical requirements].
+
This installation includes additional Ansible dependencies, such as the NetApp SANtricity software and host collections.
+
....
ansible-galaxy collection install netapp_eseries.beegfs == 3. 0.0
....
