---
sidebar: sidebar
permalink: beegfs-deploy-beegfs-configure-inventory-stepfour.html
keywords:
summary:
---

= Step 4: Configure the inventory for a storage-only building block
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This section walks you through setting up an Ansible inventory that describes a BeeGFS storage- only building block.

The major difference between setting up the configuration for a metadata + storage versus a storage- only building block is the omission of all metadata resource groups and changing `criteria_drive_count` from 10 to 12 for each storage pool.

.Steps
. In `inventory.yml`,  populate the following under the existing configuration:
+
....
      # ictad22h05/ictad22h06 HA Pair (storage only building block):
        stor_17:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_18:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_19:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_20:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_21:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_22:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_23:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_24:
          hosts:
            ictad22h06:
            ictad22h05:
....
+
. Under `group_vars/`,  create files for resource groups stor_17  stor_24 using the following template, then fill in the placeholder values for each service referencing the table:
+
....
# stor_0X - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: <PORT>
  connStoragePortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: storage
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid6
        criteria_drive_count: 12
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.50 # See note below!
            owning_controller: <OWNING CONTROLLER>
          - size: 21.50
            owning_controller: <OWNING CONTROLLER>
....
+
[NOTE]
 For  the correct size to use, see Appendix B: Recommended storage pool overprovisioning percentages <<xref>>.
+
|===
|File name |Port |Floating IPs |NUMA zone |Block node |Storage pool |Owning controller

|stor_17.yml
|8013
|i1b:100.127.103.17/16
i2b:100.128.104.17/16
|0
|ictad22a05

|beegfs_s17_s18
|A
|stor_18.yml
|8023
|i2b:100.128.104.18/16
i1b:100.127.103.18/16
|0
|ictad22a05

|beegfs_s17_s18
|B
|stor_19.yml
|8033
|i3b:100.127.103.19/16
i4b:100.128.104.19/16
|1
|ictad22a06
|beegfs_s19_s20
|A
|stor_20.yml
|8043
|i4b:100.128.104.20/16
i3b:100.127.103.20/16
|1
|ictad22a06
|beegfs_s19_s20
|B
|stor_21.yml
|8053
|i1b:100.127.103.21/16
i2b:100.128.104.21/16
|0
|ictad22a05
|beegfs_s21_s22
|A
|stor_22.yml
|8063
|i2b:100.128.104.22/16
i1b:100.127.103.22/16
|0
|ictad22a05
|beegfs_s21_s22
|B
|stor_23.yml
|8073
|i3b:100.127.103.23/16
i4b:100.128.104.23/16
|1
|ictad22a06
|beegfs_s23_s24
|A
|stor_24.yml
|8083
|i4b:100.128.104.24/16
i3b:100.127.103.24/16
|1
|ictad22a06
|beegfs_s23_s24
|B
|===
