---
sidebar: sidebar
permalink: beegfs-moreinfo.html
keywords:
summary:
---

= Where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-04-29 10:21:46.139377
//

[.lead]
To learn more about the information presented on this doc site, review the following documents and websites:

* NetApp E-Series Collections on Ansible Galaxy
+
https://galaxy.ansible.com/netapp_eseries[https://galaxy.ansible.com/netapp_eseries^]

* NetApp Product Documentation
+
https://www.netapp.com/support-and-training/documentation/[https://www.netapp.com/support-and-training/documentation/^]

* BeeGFS Documentation
+
https://doc.beegfs.io/[https://doc.beegfs.io/^]

* Interoperability Matrix Tool (IMT)
+
Refer to the http://mysupport.netapp.com/matrix[Interoperability Matrix Tool (IMT)] on the NetApp Support site to validate that the exact product and feature versions described in the NetApp Verified Architecture are supported for your specific environment.
+
The NetApp IMT defines the product components and versions that can be used to construct configurations that are supported by NetApp. Specific results depend on each customer’s installation in accordance with published specifications.

=== Version history

|===
|Version |Date |Document version history

|Version 1.0
|May 2022
|Initial release.
|===
