---
sidebar: sidebar
permalink: beegfs-design-overview.html
keywords: EF600, NetApp, BeeGFS, Verified Architecture, design
summary: "Describes the architecture and design considerations used to determine the specific equipment, cabling, and configurations required to support the BeeGFS on NetApp solution."
---

= Overview of design
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-04-29 10:21:46.030450
//

[.lead]
The NetApp Verified Architecture design describes the architecture and design considerations used to determine the specific equipment, cabling, and configurations required to support the BeeGFS on NetApp solution.

The BeeGFS on NetApp solution combines the BeeGFS parallel file system with the NetApp EF600 storage systems. The solution is:

* Thoroughly tested
* Designed to minimize deployment risks
* Designed to accelerate time to market

The BeeGFS on NetApp solution is optimized to meet the performance requirements of demanding workloads including high-performance computing (HPC) and HPC-style machine learning (ML), deep learning (DL) and similar artificial intelligence (AI) techniques.

By incorporating a shared-disk HA architecture, the BeeGFS on NetApp solution meets the data durability and availability requirements of enterprises and other organizations that cannot afford downtime or data loss as they look for storage that can scale to keep up with their next generation workloads and use cases.

The  BeeGFS on NetApp solution has not only been verified by NetApp, but it also passed external qualification as a storage option for the NVIDIA DGX SuperPOD, giving customers confidence this solution has been vetted well.
