---
sidebar: sidebar
permalink: beegfs-deploy-beegfs-configure-inventory-stepthree.html
keywords:
summary:
---

= Step 3: Configure the inventory for a Metadata + storage building block
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This section walks you through setting up an Ansible inventory that describes a BeeGFS metadata + storage building block.

.Steps
. In `inventory.yml`,  populate the following under the existing configuration:
+
....
        meta_09:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_09:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_10:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_10:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_11:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_11:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_12:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_12:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_13:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_13:
          hosts:
            ictad22h04:
            ictad22h03:
        meta_14:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_14:
          hosts:
            ictad22h04:
            ictad22h03:
        meta_15:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_15:
          hosts:
            ictad22h04:
            ictad22h03:
        meta_16:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_16:
          hosts:
            ictad22h04:
            ictad22h03:
....
+
. Under `group_vars/`,  create files for resource groups meta_09  meta_16 using the following template,  then fill in the placeholder values for each service referencing the table:
+
....
# meta_0X - BeeGFS HA Metadata Resource Group
beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: <PORT>
  connMetaPortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: metadata
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid1
        criteria_drive_count: 4
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.5 # SEE NOTE BELOW!
            owning_controller: <OWNING CONTROLLER>
....
+
[NOTE]
For the correct size to use,  see Appendix B: Recommended storage pool overprovisioning percentages <<xref>>.
+
|===
|File name |Port |Floating IPs |NUMA zone |Block node |Storage pool |Owning controller

|meta_09.yml
|8015
|i1b:100.127.101.9/16
i2b:100.128.102.9/16
|0
|ictad22a03

|beegfs_m9_m10_m13_m14
|A
|meta_10.yml
|8025
|i2b:100.128.102.10/16
i1b:100.127.101.10/16
|0
|ictad22a03

|beegfs_m9_m10_m13_m14
|B
|meta_11.yml
|8035
|i3b:100.127.101.11/16
i4b:100.128.102.11/16
|1
|ictad22a04
|beegfs_m11_m12_m15_m16
|A
|meta_12.yml
|8045
|i4b:100.128.102.12/16
i3b:100.127.101.12/16
|1
|ictad22a04
|beegfs_m11_m12_m15_m16
|B
|meta_13.yml
|8055
|i1b:100.127.101.13/16
i2b:100.128.102.13/16
|0
|ictad22a03
|beegfs_m9_m10_m13_m14
|A
|meta_14.yml
|8065
|i2b:100.128.102.14/16
i1b:100.127.101.14/16
|0
|ictad22a03
|beegfs_m9_m10_m13_m14
|B
|meta_15.yml
|8075
|i3b:100.127.101.15/16
i4b:100.128.102.15/16
|1
|ictad22a04
|beegfs_m11_m12_m15_m16
|A
|meta_16.yml
|8085
|i4b:100.128.102.16/16
i3b:100.127.101.16/16
|1
|ictad22a04
|beegfs_m11_m12_m15_m16
|B
|===
+
. Under `group_vars/,` create files for resource groups stor_09  stor_16 using the following template,  then fill in the placeholder values for each service referencing the table:
+
....
# stor_0X - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: <PORT>
  connStoragePortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: storage
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512        volumes:
          - size: 21.50 # See note below!
            owning_controller: <OWNING CONTROLLER>
          - size: 21.50            owning_controller: <OWNING CONTROLLER>
....
+
[NOTE]
 For the correct size to use, see Appendix B: Recommended storage pool overprovisioning percentages <<xref>>.
+
|===
|File name |Port |Floating IPs |NUMA zone |Block node |Storage pool |Owning controller

|stor_09.yml
|8013
|i1b:100.127.103.9/16
i2b:100.128.104.9/16
|0
|ictad22a03

|beegfs_s9_s10
|A
|stor_10.yml
|8023
|i2b:100.128.104.10/16
i1b:100.127.103.10/16
|0
|ictad22a03

|beegfs_s9_s10
|B
|stor_11.yml
|8033
|i3b:100.127.103.11/16
i4b:100.128.104.11/16
|1
|ictad22a04
|beegfs_s11_s12
|A
|stor_12.yml
|8043
|i4b:100.128.104.12/16
i3b:100.127.103.12/16
|1
|ictad22a04
|beegfs_s11_s12
|B
|stor_13.yml
|8053
|i1b:100.127.103.13/16
i2b:100.128.104.13/16
|0
|ictad22a03
|beegfs_s13_s14
|A
|stor_14.yml
|8063
|i2b:100.128.104.14/16
i1b:100.127.103.14/16
|0
|ictad22a03
|beegfs_s13_s14
|B
|stor_15.yml
|8073
|i3b:100.127.103.15/16
i4b:100.128.104.15/16
|1
|ictad22a04
|beegfs_s15_s16
|A
|stor_16.yml
|8083
|i4b:100.128.104.16/16
i3b:100.127.103.16/16
|1
|ictad22a04
|beegfs_s15_s16
|B
|===

== Step 4: Configure the inventory for a storage-only building block

This section walks you through setting up an Ansible inventory that describes a BeeGFS storage- only building block.  The major difference between setting up the configuration for a metadata + storage versus a storage- only building block is the omission of all metadata resource groups and changing `criteria_drive_count` from 10 to 12 for each storage pool.

.Steps
. In `inventory.yml`,  populate the following under the existing configuration:
+
....
      # ictad22h05/ictad22h06 HA Pair (storage only building block):
        stor_17:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_18:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_19:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_20:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_21:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_22:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_23:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_24:
          hosts:
            ictad22h06:
            ictad22h05:
....
+
. Under `group_vars/`,  create files for resource groups stor_17  stor_24 using the following template, then fill in the placeholder values for each service referencing the table:
+
....
# stor_0X - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: <PORT>
  connStoragePortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: storage
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid6
        criteria_drive_count: 12
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.50 # See note below!
            owning_controller: <OWNING CONTROLLER>
          - size: 21.50
            owning_controller: <OWNING CONTROLLER>
....
+
[NOTE]
 For  the correct size to use, see Appendix B: Recommended storage pool overprovisioning percentages <<xref>>.
+
|===
|File name |Port |Floating IPs |NUMA zone |Block node |Storage pool |Owning controller

|stor_17.yml
|8013
|i1b:100.127.103.17/16
i2b:100.128.104.17/16
|0
|ictad22a05

|beegfs_s17_s18
|A
|stor_18.yml
|8023
|i2b:100.128.104.18/16
i1b:100.127.103.18/16
|0
|ictad22a05

|beegfs_s17_s18
|B
|stor_19.yml
|8033
|i3b:100.127.103.19/16
i4b:100.128.104.19/16
|1
|ictad22a06
|beegfs_s19_s20
|A
|stor_20.yml
|8043
|i4b:100.128.104.20/16
i3b:100.127.103.20/16
|1
|ictad22a06
|beegfs_s19_s20
|B
|stor_21.yml
|8053
|i1b:100.127.103.21/16
i2b:100.128.104.21/16
|0
|ictad22a05
|beegfs_s21_s22
|A
|stor_22.yml
|8063
|i2b:100.128.104.22/16
i1b:100.127.103.22/16
|0
|ictad22a05
|beegfs_s21_s22
|B
|stor_23.yml
|8073
|i3b:100.127.103.23/16
i4b:100.128.104.23/16
|1
|ictad22a06
|beegfs_s23_s24
|A
|stor_24.yml
|8083
|i4b:100.128.104.24/16
i3b:100.127.103.24/16
|1
|ictad22a06
|beegfs_s23_s24
|B
|===
