---
sidebar: sidebar
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600
summary: "To set up an Ansible control node, identify a virtual or physical machine with network access to the management ports of all file and block nodes that can be used to configure the solution."
---

= Set up an Ansible control node
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To set up an Ansible control node, you must designate a virtual or physical machine with network access to all file and block nodes deployed for the BeeGFS on NetApp solution.

Review the link:beegfs-technology-requirements.html#ansible-control-node-requirements[Technical requirements] for a list of the currently recommended packages. The following steps were tested on Ubuntu 22.04. For steps specific to your preferred Linux distribution, see the https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible documentation^].

. From your Ansible control node, install the following Python and Python Virtual Environment packages.
+
[source,console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----

. Create a Python virtual environment
+
[source,console]
----
python3 -m venv ~/pyenv
----

. Activate the virtual environment.
+
[source,console]
----
source ~/pyenv/bin/activate
----

. Install the required Python packages within the activated virtual environment.
+
[source,console]
----
pip install ansible netaddr cryptography passlib
----

. Install the BeeGFS collection using Ansible Galaxy.
+
[source,console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----

. Verify the installed versions of Ansible, Python, and the BeeGFS collection match the requirements specified in the link:beegfs-technology-requirements.html#ansible-control-node-requirements[Technical requirements].
+
[source,console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----

. Set up passwordless SSH to allow Ansible to access the remote BeeGFS file nodes from the Ansible control node.

.. On the Ansible control node, if needed, generate a pair of public keys.
+
[source,console]
----
ssh-keygen
----

.. Set up passwordless SSH to each of the file nodes.
+
[source,console]
----
ssh-copy-id <ip_or_hostname>
----

[IMPORTANT]
Do *not* set up passwordless SSH to the block nodes. This is neither supported nor required.
