---
sidebar: sidebar
permalink: beegfs-deploy-setting-up-an-ansible-control-node.html
keywords:
summary:
---

= Setting up an Ansible control node
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-02 10:33:57.198013
//

[.lead]
Identify a virtual or physical machine that has network access to the management ports of all file and block nodes that can be used to configure the solution. The following steps were tested on CentOS 8.4.  For steps specific to your preferred Linux distribution, see the https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[ Ansible documentation^] as needed.

. Install Python 3.9 and the correct version of pip is installed.

....
sudo dnf install python3.9 -y
sudo dnf install python39-pip
sudo dnf install sshpass
....

. Create symbolic links the Python 3.9 binary is used whenever python3 or python is called.

....
sudo ln -sf /usr/bin/python3.9 /usr/bin/python3
sudo ln -sf /usr/bin/python3 /usr/bin/python
....

.  Install Python packages required by the NetApp BeeGFS collections.

....
python3 -m pip install ansible cryptography netaddr
....

[NOTE]
Always refer to the README for the version of the BeeGFS collection you’re using to ensure you are installing a supported version of Ansible and all required Python packages. These are also noted in the technology requirements section for each version of the NetApp Verified Architecture.

. Verify the installed version of Ansible and Python match what are expected.

....
ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Mar 10 2021, 17:29:56) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
....

.  strongly you store the Ansible inventories used to describe the BeeGFS deployment in source control systems such as Git or BitBucket. Install Git to interact with those systems.

....
sudo dnf install git -y
....

. The easiest way to allow Ansible to access the remote BeeGFS file nodes from the Ansible control node is by setting up passwordless SSH. On the Ansible control node, if needed,  generate a pair of public keys using `ssh-keygen`.
. Setup passwordless SSH to each of the file nodes using `ssh-copy-id <ip_or_hostname>`.
+
Do not set up passwordless SSH to the block nodesthis is neither supported nor required.

. Use Ansible Galaxy to install the version of the BeeGFS collection listed in the technology requirements section. This also install any additional Ansible dependencies including the NetApp SANtricity and host collections.

....
ansible-galaxy collection install netapp_eseries.beegfs == 3. 0.0
....

At this point you have finished configuring an Ansible control node that includes the required collections needed to deploy the solution.


