---
sidebar: sidebar
permalink: second-gen/beegfs-design-solution-sizing-guidelines.html
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600
summary: "The BeeGFS solution includes recommendations for performance and capacity sizing that were based on verification tests."
---

= Sizing guidelines
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
The BeeGFS solution includes recommendations for performance and capacity sizing that were based on verification tests.

The objective with a building-block architecture is to create a solution that is simple to size by adding multiple building blocks to meet the requirements for a particular BeeGFS system. Using the guidelines below, you can estimate the quantity and types of BeeGFS building blocks that are needed to meet the requirements of your environment.

Keep in mind that these estimates are best-case performance. Synthetic benchmarking applications are written and utilized to optimize the use of underlying file systems in ways that real-world applications might not.

== Performance sizing
The following table provides recommended performance sizing.

|===
|Configuration profile |1MiB reads |1MiB writes

|Metadata + storage
|62GiBps
|21GiBps
|Storage only
|64GiBps
|21GiBps
|===

Metadata capacity sizing estimates are based on the "rule of thumb" that 500GB of capacity is sufficient for roughly 150 million files in BeeGFS. (For more information, see the BeeGFS documentation for https://doc.beegfs.io/latest/system_design/system_requirements.html[System Requirements^].)

The use of features like access control lists and the number of directories and files per directory also affect how quickly metadata space is consumed. Storage capacity estimates do account for usable drive capacity along with RAID 6 and XFS overhead.

== Capacity sizing for metadata + storage building blocks
The following table provides recommended capacity sizing for metadata plus storage building blocks.

|===
|Drive size (2+2 RAID 1) metadata volume groups |Metadata capacity (number of files) |Drive size (8+2 RAID 6) storage volume groups |Storage capacity (file content)

|1.92TB
|1,938,577,200
|1.92TB
|51.77TB
|3.84TB
|3,880,388,400
|3.84TB
|103.55TB
|7.68TB
|8,125,278,000
|7.68TB
|216.74TB
|15.3TB
|17,269,854,000
|15.3TB
|460.60TB
|===

[NOTE]
When sizing metadata plus storage building blocks, you can reduce costs by using smaller drives for metadata volume groups versus storage volume groups.

== Capacity sizing for storage-only building blocks
The following table provides rule-of-thumb capacity sizing for storage-only building blocks.

|===
|Drive size (10+2 RAID 6) storage volume groups |Storage capacity (file content)

|1.92TB
|59.89TB
|3.84TB
|119.80TB
|7.68TB
|251.89TB
|15.3TB
|538.55TB
|===

[NOTE]
The performance and capacity overhead of including the management service in the base (first) building block are minimal, unless global file locking is enabled.
