---
sidebar: sidebar
permalink: beegfs-design-solution-sizing-guidelines.html
keywords: Sizing, EF600, NetApp, BeeGFS, Verified Architecture
summary: "Sizing guidleines for BeeGFS on NetApp solution."
---

= Sizing guidelines
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-04-29 10:21:46.134889
//

[.lead]
The objective with a building-block architecture is to create a solution that is simple to size by adding together multiple building blocks to meet the requirements for a particular BeeGFS system. Based on the verification tests above, the following table can be used to estimate the quantity and types of BeeGFS building blocks that are needed to meet the requirements of a particular environment. It is an important caveat that inevitably these estimates should always be treated as best- case performance. Synthetic benchmarking applications are written and utilized to optimize the use of underlying file systems in ways real-world applications might not.

The following table provides rule-of-thumb performance sizing.

|===
|Configuration profile |1MiB reads |1MiB writes

|Metadata + storage
|62GiBps
|21GiBps
|Storage only
|64GiBps
|21GiBps
|===

Metadata capacity sizing estimates are based on the https://doc.beegfs.io/latest/system_design/system_requirements.html[rule of thumb^] that 500GB of capacity is sufficient for roughly 150 million files in BeeGFS. The use of features like access control lists and the number of directories and files per directory also affect how quickly metadata space is consumed. Storage capacity estimates do account for usable drive capacity along with RAID 6 and XFS overhead.

The following table provides rule- of- thumb capacity sizing for metadata + storage building blocks.

|===
|Drive size (2+2 RAID 1) metadata volume groups |Metadata capacity (number of files) |Drive size (8+2 RAID 6) storage volume groups |Storage capacity (file content)

|1.92TB
|1,797,120,000
|1.92TB
|47.91TB
|3.84TB
|3,594,240,000
|3.84TB
|95.84TB
|7.68TB
|7,557,120,000
|7.68TB
|201.51TB
|15.3TB
|16,156,800,000
|15.3TB
|430.84TB
|===

[NOTE]
When sizing metadata + storage building blocks, smaller drives can be used for metadata volume groups versus storage volume groups to reduce cost.

The following table provides rule- of- thumb capacity sizing for storage-only building blocks.

|===
|Drive size (8+2 RAID 6) storage volume groups |Storage capacity (file content)

|1.92TB
|59.89TB
|3.84TB
|119.80TB
|7.68TB
|251.89TB
|15.3TB
|538.55TB
|===

[NOTE]
The performance and capacity overhead of including the management service in the base (first) building are minimal unless global file locking is enabled.
