---
sidebar: sidebar
permalink: beegfs-deploy-file-node-tuning.html
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600
summary: "To maximize performance, we recommended configuring the system settings on the server model you use as your file nodes."
---

= Tune file node system settings for performance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
To maximize performance, we recommended configuring the system settings on the server model you use as your file nodes.

The system settings vary depending on the server model you use as your file node. This topic describes how to configure the system settings for the validated Lenovo ThinkSystem SR665 server file nodes.

== Use the UEFI interface to tune system settings
The Lenovo SR665 server's system firmware contains numerous tuning parameters that can be set through the UEFI interface. These tuning parameters can affect all aspects of how the server functions and how well the server performs.

Under *UEFI Setup > System Settings*, adjust the following system settings:

=== Operating Mode menu

[cols=",",options="header",]
|===
a|
*System Setting*
a|
*Change to*
a|
Operating Mode
a|
Custom
a|
cTDP
a|
Manual
a|
cTDP Manual
a|
350
a|
Package Power Limit
a|
Manual
a|
Efficiency Mode
a|
Disable
a|
Global-Cstate-Control
a|
Disable
a|
SOC P-states
a|
P0
a|
DF C-States
a|
Disable
a|
P-State 1
a|
Disable
a|
Memory Power Down Enable
a|
Disable
a|
NUMA Nodes per Socket
a|
NPS1
|===

=== Devices and I/O ports menu

[cols=",",options="header",]
|===
a|

*System Setting*
a|
*Change to*
a|
IOMMU
a|
Disable
|===

=== Power menu

[cols=",",options="header",]
|===
a|
*System Setting*
a|
*Change to*
a|
PCIe Power Brake
a|
Disable
|===

=== Processors menu

[cols=",",options="header",]
|===
a|
*System Setting*
a|
*Change to*
a|
Global C-state Control
a|
Disable
a|DF C-States
a|
Disable
a|SMT Mode
a|
Disable
a|CPPC
a|
Disable
|===


== Use Redfish API to tune system settings
In addition to using UEFI Setup, you can use the Redfish API to change system settings.

.Example

....
curl --request PATCH \
  --url https://<BMC_IP_ADDRESS>/redfish/v1/Systems/1/Bios/Pending \
  --user <BMC_USER>:<BMC- PASSWORD> \
  --header 'Content-Type: application/json' \
  --data '{
"Attributes": {
"OperatingModes_ChooseOperatingMode": "CustomMode",
"Processors_cTDP": "Manual",
"Processors_PackagePowerLimit": "Manual",
"Power_EfficiencyMode": "Disable",
"Processors_GlobalC_stateControl": "Disable",
"Processors_SOCP_states": "P0",
"Processors_DFC_States": "Disable",
"Processors_P_state1": "Disable",
"Memory_MemoryPowerDownEnable": "Disable",
"DevicesandIOPorts_IOMMU": "Disable",
"Power_PCIePowerBrake": "Disable",
"Processors_GlobalC_stateControl": "Disable",
"Processors_DFC_States": "Disable",
"Processors_SMTMode": "Disable",
"Processors_CPPC": "Disable",
"Memory_NUMANodesperSocket":"NPS1"
}
}
'
....

For more detailed information on the Redfish schema, see the https://redfish.dmtf.org/redfish/schema_index[DMTF website].
