---
sidebar: sidebar
permalink: beegfs-technology-requirements.html
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600
summary: "To implement the BeeGFS on NetApp solution, make sure your environment meets the technology requirements."
---

= Technical requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
To implement the BeeGFS on NetApp solution, make sure your environment meets the technology requirements.

== Hardware requirements

The following table lists the hardware components that are required to implement a single second-generation building block design of the BeeGFS on NetApp solution.

NOTE: The hardware components used in any particular implementation of the solution might vary based on customer requirements.


[options="header" cols="10%,20%,70%"]
|===
|Count |Hardware component |Requirements

a|2
a| BeeGFS file node.
a|Each file node should meet or exceed the following configuration to achieve expected performance.

*Processors:*

* 2x AMD EPYC 9124 16C 200W 3.0GHz
* Configured as two NUMA zones.

*Memory:*

* 256GB.
* 16x 16GB TruDDR5 4800MHz (1Rx8) RDIMM-A (prefer more smaller DIMMs over fewer larger DIMMs).
* Populated to maximize memory bandwidth.

*PCIe Expansion: Four PCiE Gen5 x16 slots:*

* Two slots per NUMA zone.
* Each slot should provide enough power/cooling for the host card adapter.

*Miscellaneous:*

* Two drives configured in RAID 1 for the OS (1TB 7.2K SATA or better).
* 1GbE port for in-band OS management.
* 1GbE BMC with Redfish API for out-of-band server management.
* Dual hot swap power supplies and performance fans.

|2
|E-Series block node (EF600 array)
a|Each EF600 array requires the following configuration:

* Memory: 256GB (128GB per controller).
* Adapter: 2-port 200Gb/HDR (NVMe/IB).
* Drives: Configured to match desired capacity.

|8
|Nvidia ConnectX-7 HCA (for file nodes).
a|ConnectX-7 NDR200/HDR QSFP112 2-port PCIe Gen5 x16 InfiniBand Adapter

* MCX755106AS-HEAT

|8
|1m HDR InfiniBand cable (for file/block node direct connects).
a|* MCP1650-H001E30 (1m Mellanox Passive Copper cable, IB HDR, up to 200Gbps, QSFP56, 30AWG).

The length can be adjusted to account for longer distances between the file and block nodes if required.

|Varies
|Cabling for file node/storage switch connections
a|Cabling requirements vary based on the switch model used to connect file nodes to the storage leaf switch. Possible options include:

* *QM9700 Switch:*
** 4x NDR to dual NDR-200 InfiniBand splitter cables
*** Model: MFA7U10-HXXX (Nvidia active fiber cable, OSFP to 2x QSFP56, 400Gb/s to 2 x 200Gb/s). Length will vary.

* *QM8700 Switch:*
** 8x HDR InfiniBand cables. Options include:
*** Model: MCP1650-HXXX (Nvidia passive copper cable, QSFP56, 200Gb/s). Length will vary.
*** Model: MFS1S00-HXXX (Nvidia active fiber cable, QSFP56, 200Gb/s). Length will vary.

|===

== Software requirements

For predictable performance and reliability, releases of the BeeGFS on NetApp solution are tested with specific versions of the software components required to implement the solution.

=== Software deployment requirements
The following table lists the software requirements deployed automatically as part of the Ansible-based BeeGFS deployment.

[options="header" cols="20%,80%"]
|===
|Software |Version

|BeeGFS
|7.4.4
|Corosync
|3.1.5-4
|Pacemaker
|2.1.4-5
|OpenSM
a|opensm-5.17.2 (from mlnx_ofed 23.10-2.2.2.0 LTS)

NOTE: Only required for the direct connects to enable virtualization.
|===


=== Ansible control node requirements
The BeeGFS on NetApp solution is deployed and managed from an Ansible control node. For more information, see the https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html[Ansible documentation^].

The software requirements listed in the following tables are specific to the version of the NetApp BeeGFS Ansible collection listed below.

[options="header" cols="20%,80%"]
|===
|Software |Version

|Ansible
|6.0.0
When installed through pip: ansible-6.0.0 and ansible-core <2.17.0 >= 2.12.0
|Python
|3.9
|Additional Python packages
|Cryptography-43.0.0, netaddr-0.8.0, ipaddr-2.2.0
|NetApp E-Series BeeGFS Ansible Collection
|3.2.0
|===


=== File node requirements

[options="header" cols="20%,80%"]
|===
|Software |Version

a|RedHat Enterprise Linux
a|RedHat 9.3 Server Physical with High Availability (2 socket).

IMPORTANT: File nodes require a valid RedHat Enterprise Linux Server subscription and the Red Hat Enterprise Linux High Availability Add-On.
|Linux Kernel
|5.14.0-362.24.1.el9_3.x86_64
|InfiniBand / RDMA Drivers
|MLNX_OFED_LINUX-23.10-3.2.2
|ConnectX-7 HCA Firmware
| FW: 28.39.1002
PXE: 3.7.0201
UEFI: 14.32.0012
|===

=== EF600 block node requirements

[options="header" cols="20%,80%"]
|===
|Software |Version

|SANtricity OS
|11.80.0
|NVSRAM
|N6000-880834-D08.dlp
|Drive Firmware
|Latest available for the drive models in use.
|===
