---
sidebar: sidebar
permalink: beegfs-first-gen-overview.html
keywords:
summary:
---

= First generation overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-04-29 10:21:46.030450
//

[.lead]
The first generation NetApp Verified Architecture (NVA) provides customers with an IB-based architecture for high-performance workloads.

The first generation architecture is powered by NetApp EF600 NVMe storage systems, the BeeGFS parallel file system, NVIDIA DGX A100 systems, and NVIDIA Mellanox Quantum QM8700 200Gbps IB switches.

The architecture design, developed and verified by NetApp and NVIDIA, gives IT organizations an architecture that:

• Eliminates design complexities
• Allows independent scaling of compute and storage
• Enables customers to start small and scale seamlessly
• Offers a range of storage options for various performance and cost points

NetApp EF-Series AI tightly integrates DGX A100 systems, NetApp EF600 NVMe storage systems, and the BeeGFS parallel file systems with state-of-the-art IB networking. NetApp EF600 AI simplifies artificial intelligence deployments by eliminating design complexity and guesswork. Customers can start small and scale seamlessly from science experiments and proof-of-concepts to production and beyond.

To learn moe, see link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf[First Generation Design: NetApp EF-Series AI with NVIDIA DGX A100 Systems and BeeGFS]. 
