---
sidebar: sidebar
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-verify.html
keywords: BeeGFS Features, CSI, Driver
summary: "Verification of the BeeGFS CSI Driver Deployment."
---
= Verification of the BeeGFS CSI Driver Deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]

To verify that the BeeGFS CSI Driver has been deployed successfully, check the status of the CSI Driver pods and confirm that they are running as expected.

To check the status of all resources in the BeeGFS-CSI namespace, run:

[source,console]
----
kubectl get all -n beegfs-csi
----

Expected Output:
----
NAME                          READY    STATUS      RESTARTS    AGE  
pod/csi-beegfs-controller-0   3/3      Running     0           5d11h
pod/csi-beegfs-node-8f917     3/3      Running     0           5d11h
----

== Inspect Controller Pod 

To diagnose issues or gather more details about the BeeGFS CSI Controller pod, use the following command to describe the pod and review its events, status, and recent activity:

[source,console]
----
kubectl describe pod csi-beegfs-controller-0 -n beegfs-csi
----

Expected Output:
----
Events: 

  Type     Reason     Age                  From               Message 
  ----     ------     ----                 ----               ------- 
  Normal   Scheduled  117s                 default-scheduler  Successfully assigned beegfs-csi/csi-beegfs-controller-0 to node01 
  Normal   Pulled     117s                 kubelet            Container image "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0" already present on machine 
  Normal   Created    117s                 kubelet            Created container: csi-provisioner 
  Normal   Started    117s                 kubelet            Started container csi-provisioner 
  Normal   Started    101s (x3 over 117s)  kubelet            Started container beegfs 
  Normal   Pulled     86s (x2 over 117s)   kubelet            Container image "registry.k8s.io/sig-storage/csi-resizer:v1.11.1" already present on machine 
  Normal   Created    86s (x2 over 117s)   kubelet            Created container: csi-resizer 
  Normal   Started    86s (x2 over 117s)   kubelet            Started container csi-resizer 
  Warning  BackOff    85s (x5 over 115s)   kubelet            Back-off restarting failed container beegfs in pod csi-beegfs-controller-0_beegfs-csi(47016fd3-3a2a-41ed-bc4c-5a716c377b1e) 
  Normal   Pulled     73s (x4 over 117s)   kubelet            Container image "ghcr.io/thinkparq/beegfs-csi-driver:v1.7.0" already present on machine 
  Normal   Created    73s (x4 over 117s)   kubelet            Created container: beegfs 
----

== Verify StorageClass 

. Validate the StorageClass was created successfully: 
+
[source,console]
----
kubectl get sc
----
+
Expected Output:
+
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl get sc  
NAME                PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE 
csi-beegfs-dyn-sc   beegfs.csi.org.com   Delete          Immediate           true                   17s 
----

. Confirm that the BeeGFS volume is mounted as expected.
+
Verify the directory specified as `volDirBasePath` in `examples/k8s/dyn/dyn-sc.yaml` appears under `/mnt/beegfs`.
+
For example, if `volDirBasePath` is set to `user_id_k8s`, you should see this directory listed:
+
[source,console]
----
root@node01:/# ls -ltr /mnt/beegfs/
total 1
drwxrwxrwx 4 root root 2 Oct 15 10:16 user_id_k8s
----

