---
sidebar: sidebar
permalink: custom-architectures-setup-nodes.html
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600
summary: "Manual steps required to set up file and block nodes before running Ansible."
---
= Set Up File and Block Nodes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
Manual steps required to set up file and block nodes before running Ansible.

== File Nodes 

=== Configure the Baseboard Management Controller (BMC)

A baseboard management controller (BMC), sometimes referred to as a service processor, is the generic name for the out-of-band management capability built into various server platforms that can provide remote access even if the operating system is not installed or accessible. Vendors typically market this functionality with their own branding. For example, on the Lenovo SR665, the BMC is referred to as the Lenovo XClarity Controller (XCC).

Follow the server vendor's documentation to enable any licenses needed to access this functionality and ensure the BMC is connected to the network and configured appropriately for remote access.

NOTE: If BMC based fencing using Redfish is desired, ensure Redfish is enabled and the BMC interface is accessible from the OS installed on the file node. Special configuration may be required on the network switch if the BMC and operating share the same physical network interface.

=== Tune System Settings

Using the system setup (BIOS/UEFI) interface, ensure settings are set to maximize performance. The exact settings and optimal values will vary based on the server model in use. Guidance is provided for link:beegfs-deploy-file-node-tuning.html[verified file node models^], otherwise refer to the server vendor's documentation and best practices based on your model.

=== Install an Operating System

Install a supported operating system based on the file node requirements listed link:beegfs-technology-requirements.html#file-node-requirements[here^]. Refer to any additional steps below based on your Linux distribution.

==== RedHat
Use RedHat Subscription Manager to register and subscribe the system to allow installation of the required packages from the official Red Hat repositories and to limit updates to the supported version of Red Hat: `subscription-manager release --set=<MAJOR_VERSION>.<MINOR_VERSION>`. For instructions, see https://access.redhat.com/solutions/253273[How to register and subscribe a RHEL system^] and  https://access.redhat.com/solutions/2761031[How to limit updates^].

Enable the Red Hat repository containing the packages required for high availability:

....
subscription-manager repo-override --repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
....

=== Configure Management Network

Configure any network interfaces needed to allow in-band management of the operating system. The exact steps will depend on the specific Linux distribution and version in use.

NOTE: Ensure SSH is enabled and all management interfaces are accessible from the Ansible control node.

=== Update HCA and HBA Firmware

Ensure all HBAs and HCAs are running supported firmware versions listed on the link:https://imt.netapp.com/matrix/[NetApp Interoperability Matrix^] and upgrade if necessary. Additional recommendations for NVIDIA ConnectX adapters can be found link:beegfs-technology-requirements.html#file-node-requirements[here^].

== Block Nodes

Follow the steps to link:https://docs.netapp.com/us-en/e-series/getting-started/getup-run-concept.html[get up and running with E-Series^] to configure the management port on each block node controller and optionally set the storage array name for each system. 

NOTE: No additional configuration beyond ensuring all block nodes are accessible from the Ansible control node is necessary. The remaining system configuration will be applied/maintained using Ansible.
