---
sidebar: sidebar
permalink: administer/clusters-update-beegfs-v7.html
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade
summary: "Update BeeGFS 7.4.6 and below using Ansible."
---
= Update BeeGFS 7.4.6 and below
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
Follow these steps to update your HA cluster between BeeGFS 7.x versions.

== Overview

This procedure covers upgrading between BeeGFS 7.x versions, including updates to patch, minor, or major versions within the BeeGFS 7.x release family. Use Ansible to perform all BeeGFS upgrades for consistent and reliable updates.

NOTE: If you are upgrading to BeeGFS v8, see the link:clusters-update-beegfs-v8.html[Upgrade to BeeGFS v8] procedure instead.

== Tested upgrade paths

The following upgrade paths have been tested and verified for BeeGFS 7.x versions:

[cols="1,1,1,5" options="header"]
|===
| Original Version | Upgrade Version | Multirail | Details                                                            
| 7.2.6            | 7.3.2           | Yes       | Upgrading beegfs collection from v3.0.1 to v3.1.0, multirail added
| 7.2.6            | 7.2.8           | No        | Upgrading beegfs collection from v3.0.1 to v3.1.0
| 7.2.8            | 7.3.1           | Yes       | Upgrade using beegfs collection v3.1.0, multirail added
| 7.3.1            | 7.3.2           | Yes       | Upgrade using beegfs collection v3.1.0
| 7.3.2            | 7.4.1           | Yes       | Upgrade using beegfs collection v3.2.0
| 7.4.1            | 7.4.2           | Yes       | Upgrade using beegfs collection v3.2.0
| 7.4.2            | 7.4.6           | Yes       | Upgrade using beegfs collection v3.2.0
|===

== Upgrade procedure

The BeeGFS 7.x upgrade process uses Ansible to automatically handle package updates and cluster management.

=== Step 1: Upgrade BeeGFS collection

For collection upgrades with access to link:https://galaxy.ansible.com/netapp_eseries/beegfs[Ansible Galaxy^], run the following command: 

[source,console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----

For offline collection upgrades, download the collection from link:https://galaxy.ansible.com/netapp_eseries/beegfs[Ansible Galaxy^] by clicking on the desired `Install Version`` and then `Download tarball`. Transfer the tarball to your Ansible control node and run the following command.

[source,console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----

See link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html[Installing Collections^] for more information.

=== Step 2: Update Ansible inventory

Make any required or desired updates to your cluster's Ansible inventory files. See the <<Version upgrade notes>> section below for details about your specific upgrade requirements. See the link:../custom/architectures-inventory-overview.html[Ansible Inventory Overview^] section for general information on configuring your BeeGFS HA inventory.

=== Step 3: Update Ansible playbook (when updating major or minor versions only)

If you are moving between major or minor versions, in the `playbook.yml` file used to deploy and maintain the cluster, update the name of the `beegfs_ha_<VERSION>` role to reflect the desired version. For example, if you wanted to deploy BeeGFS 7.4 this would be `beegfs_ha_7_4`:

[source,yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----

For more details on the contents of this playbook file see the link:../custom/architectures-deploy-ha-cluster.html[Deploy the BeeGFS HA cluster^] section.

=== Step 4: Run the BeeGFS upgrade

To apply the BeeGFS update:

[source,console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----

Behind the scenes the BeeGFS HA role will handle:

* Ensure the cluster is in an optimal state with each BeeGFS service located on its preferred node.
* Put the cluster in maintenance mode.
* Update the HA cluster components (if needed).
* Upgrade each file node one at a time as follows:
** Place it into standby and failover its services to the secondary node.
** Upgrade BeeGFS packages.
** Fallback back services.
* Move the cluster out of maintenance mode.

== Version upgrade notes

=== Upgrading from BeeGFS version 7.2.6 or 7.3.0

==== Changes to connection based authentication

BeeGFS versions released after 7.3.1 will no longer allow services to start without either specifying a `connAuthFile` or setting `connDisableAuthentication=true` in the service's configuration file. It is highly recommended to enable connection based authentication security. See link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth[BeeGFS Connection Based Authentication^] for more information.

By default the `beegfs_ha*` roles will generate and distribute this file, also adding it to the Ansible control node at `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`. The `beegfs_client` role will also check for the presence of this file and supply it to the clients if available.

WARNING: If the `beegfs_client` role was not used to configure clients, this file will need to be manually distributed to each client and the `connAuthFile` configuration in the `beegfs-client.conf` file set to use it. When upgrading from a previous version of BeeGFS where connection based authentication was not enabled, clients will loose access unless connection based authentication is disabled as part of the upgrade by setting `beegfs_ha_conn_auth_enabled: false` in `group_vars/ha_cluster.yml` (not recommended).

For additional details and alternate configuration options see the step to configure connection authentication in the link:../custom/architectures-inventory-common-file-node-configuration.html[Specify Common File Node Configuration^] section.
