---
sidebar: sidebar
permalink: administer/clusters-update-hca-firmware.html
keywords: BeeGFS on NetApp, HA, Cluster, Administration, Update, Upgrade, HCA, ConnectX, Firmware, Card, Adapter
summary: "Steps to update the file node's ConnectX-7 adapter firmware."
---
= Update file node adapter firmware
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
Follow these steps to update the file node's ConnectX-7 adapters to the latest firmware.

== Overview

Updating the ConnectX-7 adapter firmware may be required to support a new MLNX_OFED driver, enable new features, or fix bugs. You can update the firmware on each file node using NVIDIA's `mlxfwmanager` or `flint` utilities. Choose the appropriate update method according to your cluster's size.

*Rolling update*

Recommended for any HA cluster with more than two nodes. This process involves updating adapter firmware one file node at a time, allowing the HA cluster to keep servicing requests, though it is recommended to avoid servicing I/O during this time.

*Single building block update*

Recommended for HA clusters with only two nodes. It is similar to a rolling update but includes additional steps to prevent service downtime when a node reboots.

IMPORTANT: Before performing firmware updates, ensure you have valid backup of your BeeGFS filesystem, confirm the cluster is healthy, and verify a compatible MLNX_OFED driver is installed.

== Firmware update tools

There are multiple tools available to update a node's adapter firmware. Below are a couple methods to update the firmware image for NVIDIA adapters. Each utility comes bundled with NVIDIA's mlnx_ofed driver.

*Online firmware update*

If the cluster has internet access, use the `mlxfwmanager` tool to query and update the firmware on all NVIDIA adapters:
[source,console]
----
mlxfwmanager
----
NOTE: For Lenovo ConnectX-7 adapters, use the `mlxfwmanager_LES` tool available on NVIDIA’s link:https://network.nvidia.com/support/firmware/lenovo-intelligent-cluster/[OEM firmware^] page.

*Offline firmware update*

If the cluster does not have internet access, use the `flint` tool to manually update firmware. First, download the adapter's firmware image from NVIDIA's support site and store it on the file node. Then, update the adapter using flint:

. List the node's adapters and their corresponding PCI address:
+
[source,console]
----
mst status
----

. For each adapter targeted for update, run:
+
[source,console]
----
flint -d <adapter_pci_address> -i </path/to/firmware.bin> b
----

== Rolling update procedure

. Confirm that the cluster is in an optimal state, with each BeeGFS service running on its preferred node. Refer to link:clusters-examine-state.html[Examine the state of the cluster^] for details.

. Choose a file node to update and place it into standby mode, which drains (or moves) all BeeGFS services from that node:
+
[source,console]
----
pcs node standby <HOSTNAME>
----

. Verify that the node's services have drained by running:
+
[source,console]
----
pcs status
----
Verify no services are reporting as `Started` on the node in standby.
+
TIP: Depending on cluster size, it may take seconds or minutes for BeeGFS services to move to the sister node. If a BeeGFS service fails to start on the sister node, refer to the link:clusters-troubleshoot.html[Troubleshooting Guides^].

. Once resources are fully drained, update the adapter firmware using one of the <<Firmware update tools,firmware update tools>>.

. Reboot the node after the firmware update completes.

. After reboot, verify that all adapters are at the desired firmware version:
+
[source,console]
----
ibstat
----

. Start Pacemaker cluster services on the node:
+
[source,console]
----
pcs cluster start <HOSTNAME>
----

. Bring the node out of standby:
+
[source,console]
----
pcs node unstandby <HOSTNAME>
----

. Relocate all BeeGFS services back to their preferred node:
+
[source,console]
----
pcs resource relocate run
----

Repeat these steps for each file node in the cluster until all adapters are updated.

== Single building block update procedure

. Confirm that the cluster is in an optimal state, with each BeeGFS service running on its preferred node. Refer to link:clusters-examine-state.html[Examine the state of the cluster^] for details.
+
. Choose a file node to update and place the node in standby mode, which drains (or moves) all BeeGFS services from that node:
+
[source,console]
----
pcs node standby <HOSTNAME>
----
+
. Place the cluster into maintenance mode.
+
[source,console]
----
pcs property set maintenance-mode=true
----
+
. Verify that the node's resources have drained by running:
+
[source,console]
----
pcs status
----
+
TIP: Depending on cluster size, it may take seconds or minutes for BeeGFS services to report as `Started` on the sister node. If a BeeGFS service fails to start, refer to the link:clusters-troubleshoot.html[Troubleshooting Guides^].

. Once resources are fully drained, update the adapter firmware using one of the <<Firmware update tools,firmware update tools>>.
+
. Reboot the node after the firmware update completes.
+
. After reboot, start Pacemaker cluster services:
+
[source,console]
----
pcs cluster start <HOSTNAME>
----

. Bring the node out of standby:
+
[source,console]
----
pcs node unstandby <HOSTNAME>
----
+
. Take the cluster out of maintenance mode.
+
[source,console]
----
pcs property set maintenance-mode=false
----
+
. Relocate all BeeGFS services back to their preferred node:
+
[source,console]
----
pcs resource relocate run
----

Repeat these steps for each file node in the cluster until all adapters are updated.