---
sidebar: sidebar
permalink: administer/clusters-update-ha-services.html
keywords: Cluster, Administration, Update, Upgrade, Pacemaker, Corosync
summary: "Steps to upgrade Pacemaker and Corosync packages in an HA cluster."
---
= Upgrade Pacemaker and Corosync packages in an HA cluster
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
Follow these steps to upgrade Pacemaker and Corosync packages in an HA cluster.

== Overview

Upgrading Pacemaker and Corosync ensures the cluster benefits from new features, security patches, and performance improvements.

[IMPORTANT]
====
Before initiating an upgrade, verify that:

* The new Pacemaker and Corosync packages are supported within the NetApp BeeGFS solution.
* Valid backups exist for your BeeGFS filesystem and Pacemaker cluster configuration.
* The cluster is in a healthy state.
====

== Upgrade Approach

There are two approaches to upgrading a cluster: a complete cluster shutdown or a rolling upgrade. Each approach has its own advantages and disadvantages. Your upgrade procedure may vary depending on your Pacemaker release version. Refer to ClusterLabs' link:https://clusterlabs.org/projects/pacemaker/doc/3.0/Pacemaker_Administration/html/upgrading.html[Upgrading a Pacemaker Cluster^] documentation to determine which approach to use.

=== Complete Cluster Shutdown

In this method, all cluster nodes and resources are shut down, the nodes are upgraded, and then the cluster is restarted. This approach is necessary if the Pacemaker and Corosync versions do not support a mixed-version configuration.

. Confirm that the cluster is in an optimal state, with each BeeGFS service running on its preferred node. Refer to link:clusters-examine-state.html[Examine the state of the cluster^] for details.

. Shut down the cluster software (Pacemaker and Corosync) on all nodes.
+
[source,console]
----
pcs cluster stop --all
----
+
TIP: Depending on the cluster size, it may take seconds or minutes for the entire cluster to stop.

. Once cluster services have shut down on all nodes, upgrade the Pacemaker and Corosync packages on each node according to your requirements.
+
NOTE: Package manager commands will vary by operating system. The following examples use RHEL:
+
[source,console]
----
dnf update pacemaker-<version>
----
+
[source,console]
----
dnf update corosync-<version>
----
+
. Verify the configuration on the first upgraded node using the crm_verify tool:
+
[source,console]
----
crm_verify -L -V
----
+
This command ensures that the cluster configuration is valid with the new package versions.

. After upgrading all nodes, start the cluster software on each node:
+
[source,console]
----
pcs cluster start --all
----

=== Rolling Upgrade

This method involves removing each node from the cluster, upgrading it, and then reintroducing it into the cluster until all nodes run the new version. This approach keeps the cluster operational, which is ideal for larger HA clusters, but carries the risk of running mixed versions during the process.

. Confirm that the cluster is in an optimal state, with each BeeGFS service running on its preferred node. Refer to link:clusters-examine-state.html[Examine the state of the cluster^] for details.

. For the node to be upgraded, place it into standby mode to drain (or move) all BeeGFS services:
+
[source,console]
----
pcs node standby <HOSTNAME>
----
+
. Verify that the node's services have drained by running:
+
[source,console]
----
pcs status
----
Ensure no services are reported as `Started` on the node in standby.
+
TIP: Depending on your cluster size, it may take seconds or minutes for services to shift to their sister node. If a BeeGFS service fails to start on the sister node, refer to link:clusters-troubleshoot.html[Troubleshooting Guides^].

. Shut down the cluster on the node:
+
[source,console]
----
pcs cluster stop <HOSTNAME>
----
+
. Upgrade the Pacemaker and Corosync packages on the node:
+
NOTE: The package manager commands will vary by operating system. The examples below are for RHEL 9:
+
[source,console]
----
dnf update pacemaker-<version>
----
+
[source,console]
----
dnf update corosync-<version>
----
+
. Verify the configuration with the crm_verify tool on the first upgraded node:
+
[source,console]
----
crm_verify -L -V
----
+
. Start the Pacemaker cluster services on the node:
+
[source,console]
----
pcs cluster start <HOSTNAME>
----
+
. Bring the node out of standby:
+
[source,console]
----
pcs node unstandby <HOSTNAME>
----
+
. Relocate all BeeGFS services back to their preferred node:
+
[source,console]
----
pcs resource relocate run
----
+
. Repeat these steps for each node until all are upgraded to the desired Pacemaker and Corosync versions.

When the package upgrades are complete, confirm that the cluster is healthy:

[source,console]
----
pcs status
----

NOTE: If any upgraded node is unable to rejoin the cluster or if resources fail to start, check the cluster logs and consult the Pacemaker release notes or user guides for known upgrade issues.