---
sidebar: sidebar
permalink: custom/architectures-deploy-beegfs-clients.html
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600
summary: "Optionally, Ansible can be used to configure BeeGFS clients and mount the file system."
---
= Deploy BeeGFS clients
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
Optionally, Ansible can be used to configure BeeGFS clients and mount the file system.

== Overview
Accessing BeeGFS file systems requires installing and configuring the BeeGFS client on each node that needs to mount the file system. This section documents how to perform these tasks using the available link:https://github.com/netappeseries/beegfs/tree/master/roles/beegfs_client[Ansible role^].

== Steps

=== Create the Client Inventory File 

. If needed, set up passwordless SSH from the Ansible control node to each of the hosts you want to configure as BeeGFS clients:
+
[source,bash]
----
ssh-copy-id <user>@<HOSTNAME_OR_IP>
----
. Under `host_vars/`, create a file for each BeeGFS client named `<HOSTNAME>.yml` with the following content, filling in the placeholder text with the correct information for your environment:
+
[source,yaml]
----
# BeeGFS Client
ansible_host: <MANAGEMENT_IP>
----
. Optionally include one of the following if you want to use the NetApp E-Series Host Collection's roles to configure InfiniBand or Ethernet interfaces for clients to connect to BeeGFS file nodes:
.. If the network type is link:https://github.com/netappeseries/host/tree/release-1.2.0/roles/ipoib[InfiniBand (using IPoIB)^]: 
+
[source,yaml]
----
eseries_ipoib_interfaces:
- name: <INTERFACE>  # Example: ib0 or i1b
  address: <IP/SUBNET> # Example: 100.127.100.1/16
- name: <INTERFACE>  # Additional interfaces as needed.
  address: <IP/SUBNET>
----
.. If the network type is link:https://github.com/netappeseries/host/tree/release-1.2.0/roles/roce[RDMA over Converged Ethernet (RoCE)^]: 
+
[source,yaml]
----
eseries_roce_interfaces:
- name: <INTERFACE>  # Example: eth0.
  address: <IP/SUBNET> # Example: 100.127.100.1/16
- name: <INTERFACE>  # Additional interfaces as needed.
  address: <IP/SUBNET>
----
.. If the network type is link:https://github.com/netappeseries/host/tree/release-1.2.0/roles/ip[Ethernet (TCP only, no RDMA)^]: 
+
[source,yaml]
----
eseries_ip_interfaces:
- name: <INTERFACE>  # Example: eth0.
  address: <IP/SUBNET> # Example: 100.127.100.1/16
- name: <INTERFACE>  # Additional interfaces as needed.
  address: <IP/SUBNET>
----
. Create a new file `client_inventory.yml` and specify the user Ansible should use to connect to each client, and the password Ansible should use for privilege escalation (this requires `ansible_ssh_user` be root, or have sudo privileges):
+
[source,yaml]
----
# BeeGFS client inventory.
all:
  vars:
    ansible_ssh_user: <USER>
    ansible_become_password: <PASSWORD>
----
IMPORTANT: Do not store passwords in plain text. Instead, use the Ansible Vault (see the link:https://docs.ansible.com/ansible/latest/user_guide/vault.html[Ansible documentation^] for Encrypting content with Ansible Vault) or use the `--ask-become-pass` option when running the playbook.

. In the `client_inventory.yml` file, list all hosts that should be configured as BeeGFS clients under the `beegfs_clients` group, and then refer to the inline comments and uncomment any additional configuration required to build the BeeGFS client kernel module on your system:
+
[source,yaml]
----
children:
    # Ansible group representing all BeeGFS clients:
    beegfs_clients:
      hosts:
        <CLIENT HOSTNAME>:
        # Additional clients as needed. 

      vars:
        # OPTION 1: If you’re using the NVIDIA OFED drivers and they are already installed:
        #eseries_ib_skip: True # Skip installing inbox drivers when using the IPoIB role.
        #beegfs_client_ofed_enable: True
        #beegfs_client_ofed_include_path: "/usr/src/ofa_kernel/default/include"

        # OPTION 2: If you’re using inbox IB/RDMA drivers and they are already installed:
        #eseries_ib_skip: True # Skip installing inbox drivers when using the IPoIB role.

        # OPTION 3: If you want to use inbox IB/RDMA drivers and need them installed/configured.
        #eseries_ib_skip: False # Default value.
        #beegfs_client_ofed_enable: False # Default value.
----
NOTE: When using the NVIDIA OFED drivers, make sure that beegfs_client_ofed_include_path points to the correct "header include path" for your Linux installation. For more information, see the BeeGFS documentation for link:https://doc.beegfs.io/latest/advanced_topics/rdma_support.html[RDMA support^].

. In the `client_inventory.yml` file, list the BeeGFS file systems you want mounted under any previously defined `vars`:
+
[source,yaml]
----
        beegfs_client_mounts:
          - sysMgmtdHost: <IP ADDRESS>  # Primary IP of the BeeGFS management service.
            mount_point: /mnt/beegfs    # Path to mount BeeGFS on the client.
            connInterfaces:
              - <INTERFACE> # Example: ibs4f1
              - <INTERFACE>
            beegfs_client_config:
              # Maximum number of simultaneous connections to the same node.
              connMaxInternodeNum: 128 # BeeGFS Client Default: 12
              # Allocates the number of buffers for transferring IO.
              connRDMABufNum: 36 # BeeGFS Client Default: 70
              # Size of each allocated RDMA buffer
              connRDMABufSize: 65536 # BeeGFS Client Default: 8192
              # Required when using the BeeGFS client with the shared-disk HA solution.
              # This does require BeeGFS targets be mounted in the default “sync” mode.
              # See the documentation included with the BeeGFS client role for full details.
              sysSessionChecksEnabled: false
        # Specify additional file system mounts for this or other file systems.
----
. As of BeeGFS 7.2.7 and 7.3.1 link:https://doc.beegfs.io/latest/advanced_topics/authentication.html[connection authentication^] must be configured or explicitly disabled. Depending how you choose to configure connection based authentication when specifying link:architectures-inventory-common-file-node-configuration.html[common file node configuration^], you may need to adjust your client configuration: 
.. By default the HA cluster deployment will automatically configure connection authentication, and generate a `connauthfile` that will be placed/maintained on the Ansible control node at `<INVENTORY>/files/beegfs/<sysMgmtdHost>_connAuthFile`. By default the BeeGFS client role is setup to read/distribute this file to the clients defined in `client_inventory.yml`, and no additional action is needed.
... For advanced options refer to the full list of defaults included with the link:https://github.com/netappeseries/beegfs/blob/release-3.1.0/roles/beegfs_client/defaults/main.yml#L32[BeeGFS client role^].
.. If you choose to specify a custom secret with `beegfs_ha_conn_auth_secret` specify it in the `client_inventory.yml` file as well:
+
[source,yaml]
----
beegfs_ha_conn_auth_secret: <SECRET>
----
.. If you choose to disable connection based authentication entirely with `beegfs_ha_conn_auth_enabled`, specify that in the `client_inventory.yml` file as well:
+
[source,yaml]
----
beegfs_ha_conn_auth_enabled: false
----

For a full list of supported parameters and additional details refer to the link:https://github.com/netappeseries/beegfs/tree/master/roles/beegfs_client[full BeeGFS client documentation^]. For a complete example of a client inventory click link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/client_inventory.yml[here^].

=== Create the BeeGFS Client Playbook File

. Create a new file `client_playbook.yml` 
+
[source,yaml]
----
# BeeGFS client playbook.
- hosts: beegfs_clients
  any_errors_fatal: true
  gather_facts: true
  collections:
    - netapp_eseries.beegfs
    - netapp_eseries.host
  tasks:
----
. Optional: If you want to use the NetApp E-Series Host Collection's roles to configure interfaces for clients to connect to BeeGFS file systems, import the role corresponding with the interface type you are configuring: 
.. If you are using are using InfiniBand (IPoIB):
+
[source,yaml]
----
    - name: Ensure IPoIB is configured
      import_role:
        name: ipoib
----
.. If you are using are using RDMA over Converged Ethernet (RoCE):
+
[source,yaml]
----
    - name: Ensure IPoIB is configured
      import_role:
        name: roce
----
.. If you are using are using Ethernet (TCP only, no RDMA):
+
[source,yaml]
----
    - name: Ensure IPoIB is configured
      import_role:
        name: ip
----
. Lastly import the BeeGFS client role to install the client software and setup the file system mounts:
+
[source,yaml]
----
    # REQUIRED: Install the BeeGFS client and mount the BeeGFS file system.
    - name: Verify the BeeGFS clients are configured.
      import_role:
        name: beegfs_client
----

For a complete example of a client playbook click link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/client_playbook.yml[here^].

=== Run the BeeGFS Client Playbook

To install/build the client and mount BeeGFS, run the following command:

[source,bash]
----
ansible-playbook -i client_inventory.yml client_playbook.yml
----