---
sidebar: sidebar
permalink: beegfs-features/beegfs-csi-driver/csi-driver-deploy.html
keywords: BeeGFS Features, CSI, Driver
summary: "Deployment of the BeeGFS CSI Driver."
---
= Deployment of the BeeGFS CSI Driver
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
Instructions for deploying the BeeGFS CSI Driver.


== Overview 

The BeeGFS CSI Driver enables Kubernetes clusters to dynamically provision and manage BeeGFS volumes, integrating BeeGFS storage with containerized workloads.

 

== Deployment Steps

=== Prepare for Deployment

Before deploying the BeeGFS CSI Driver, ensure that you have completed all pre-requisites outlined in the previous section. This includes verifying your Kubernetes setup, validating the BeeGFS client and services, and preparing any air-gapped nodes if necessary.

==. Offline Access: 
If you only have offline access, download the BeeGFS-CSI driver repo from your internal server. 

. Retrieve Images for Offline Deployment 

Offline deployment refers to the unavailability of the internet to download container images needed for CSI-Driver. In this case, both the kubernetes yaml files and the container images need to be downloaded in advance and copied to the system where the CSI driver setup is to be done. The kubernetes yaml files can be downloaded from this Github repository: 

[source,console]
----
git clone https://github.com/ThinkParQ/beegfs-csi-driver.git 
----
The PS team can provide the path of the location to download the container images. 

Please follow the below mentioned steps for doing the offline deployment of CSI Driver: 
[.indented]
====
. Save the “beegfs-csi-driver" folder downloaded from Git to the directory:
[source,shell]
----
  /home/<User>/beegfs-csi-driver  
----
. Save the images downloaded from the location provided by the PS team in the directory: 
[source,shell]
----
  /home/<User>/beegfs-csi-images  
----
Since this Kubernetes setup depends on containerd for image management, these images which are saved as .tar files need to be uploaded to containerd 
. Navigate to the directory where the images are saved (/home/<User>/beegfs-csi-images). 
. Run the following commands to load the images: 
# Loading these docker images saved in local directory to containerd: 
[source,shell]
----
ctr -n k8s.io images import beegfs-csi-driver_v1.7.0.tar 
----
[source,shell]
----
ctr -n k8s.io images import csi-provisioner_v3.5.0.tar
----
[source,shell]
----
ctr -n k8s.io images import csi-resizer_v1.11.1.tar
----
[source,shell]
----
ctr -n k8s.io images import livenessprobe_v2.10.0.tar
----
[source,shell]
----
ctr -n k8s.io images import csi-node-driver-registrar_v2.8.0.tar
----

. Run the following command to check if the images are loaded in containerd: 
[source,shell]
----
crictl images 
----
OPTIONAL: Visit section 4.5 to get details regarding how to download and save images locally. 

. Navigate to the “beegfs-csi-driver" folder which is downloaded from git 
[source,shell]
----
cd /home/<User>/beegfs-csi-driver 
----
The default overlay configurations are intended for online deployment. Because we are performing offline deployment, we cannot use these default overlay configurations. Copy the “default” folder to something like “my-overlay”:  
[source,shell]
----
cp -r deploy/k8s/overlays/default deploy/k8s/overlays/my-overlay 
----

. Open the `deploy/k8s/overlays/my-overlay/kustomization.yaml` file to uncomment the image section and add the changes.  
. Uncomment The `images` section and add the following information: (digest can remain commented): 
[source,shell]
----
images: 

  - name: ghcr.io/thinkparq/beegfs-csi-driver 

    newTag: v1.7.0 

    # digest: sha256:eb7ff01259e6770d0103f219e11b7ff334c9d9102a29ea0af95a3c0d7aec1ae3 

  - name: k8s.gcr.io/sig-storage/csi-provisioner 

    newName: registry.k8s.io/sig-storage/csi-provisioner 

    newTag: v3.5.0 

  - name: k8s.gcr.io/sig-storage/csi-resizer 

    newName: registry.k8s.io/sig-storage/csi-resizer 

    newTag: v1.11.1 

  - name: k8s.gcr.io/sig-storage/livenessprobe 

    newName: registry.k8s.io/sig-storage/livenessprobe 

    newTag: v2.10.0 

  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar 

    newName: registry.k8s.io/sig-storage/csi-node-driver-registrar 

    newTag: v2.8.0 
----
. After updating the images, we need to ensure that Kubernetes is forced to use the images configured locally in `containerd` and not from the web. The default image-pull policy is “Always” which refers to “always pull the latest docker images”. This needs to be changed to “Never”. To do this, we need to add a file in `deploy/k8s/overlays/my-overlay/` folder. The file should be named: `image-pull-policy.yaml`. This is the content of the yaml file: 
[source,shell]
---- 
# Patch for controller 

kind: StatefulSet 

apiVersion: apps/v1 

metadata: 

  name: csi-beegfs-controller 

spec: 

  template: 

    spec: 

      containers: 

        - name: beegfs 

          imagePullPolicy: Never 

        - name: csi-provisioner 

          imagePullPolicy: Never 

        - name: csi-resizer 

          imagePullPolicy: Never 

 

# Patch for node 

--- 

kind: DaemonSet 

apiVersion: apps/v1 

metadata: 

  name: csi-beegfs-node 

spec: 

  template: 

    spec: 

      containers: 

        - name: beegfs 

          imagePullPolicy: Never 

        - name: node-driver-registrar 

          imagePullPolicy: Never 

        - name: liveness-probe 

          imagePullPolicy: Never 
----
. Refer the  yaml file for “image-pull-policy" in the “kustomization.yaml” file in `patchesStrategicMerge` section. Add a new entry for the path of the new yaml file: 
[source,shell]
---- 
patches/image-pull-policy.yaml 
---- 
 NOTE: Since Kubernetes is referring to containerd for getting its images, we are referencing images loaded in containerd. If Kubernetes is configured to load images from Docker, then the images would be used from docker daemon. In either case, the image-pull-policy yaml file is going to remain the same. 
[.indented] 

====

==. Online Access - GithubRepo:
If you have online web access and you are on a machine with kubectl and access to the Kubernetes cluster where you want to deploy the BeeGFS CSI driver, clone this repository:
git clone https://github.com/ThinkParQ/beegfs-csi-driver.git.

When we deploy the pods, it would automatically download the images from image-hub and spin the required services. You need not set them up beforehand. 

=== Deploy the BeeGFS CSI Driver

Go to the repository directory and verify that all required files are available. If the necessary settings are already configured in beegfs-client.conf, you can proceed with the default configuration to deploy the CSI driver, as it will function out-of-the-box. If not, adjust the settings in the overlay to specify the desired values. 

[source,shell]
----
root@node01:/home/<USER># nano deploy/k8s/overlays/default/

csi-beegfs-config.yaml      csi-beegfs-connauth.yaml      kustomization.yaml      namespace.yaml      patches/
----

NOTE: The CSI driver requires the configuration file to be located at /etc/beegfs/beegfs-client.conf and to have that exact name. If your configuration file has a different name, create a symbolic link named beegfs-client.conf pointing to your existing file. 

== Deploy the default overlays:

[source,console]
----
kubectl apply -f deploy/k8s/overlays/default
----

Expected Output:

[source,shell]
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl apply -k deploy/k8s/overlays/my-overlay 
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically. 
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically. 
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically. 
namespace/beegfs-csi created 
serviceaccount/csi-beegfs-controller-sa created 
serviceaccount/csi-beegfs-node-sa created 
role.rbac.authorization.k8s.io/csi-beegfs-privileged-scc-role created 
clusterrole.rbac.authorization.k8s.io/csi-beegfs-provisioner-role created 
rolebinding.rbac.authorization.k8s.io/csi-beegfs-privileged-scc-binding created 
clusterrolebinding.rbac.authorization.k8s.io/csi-beegfs-provisioner-binding created 
configmap/csi-beegfs-config-kkc8fg68fh created 
secret/csi-beegfs-connauth-b8kbm2mmm2 created 
statefulset.apps/csi-beegfs-controller created 
daemonset.apps/csi-beegfs-node created 
csidriver.storage.k8s.io/beegfs.csi.netapp.com created 
----
