---
sidebar: sidebar
permalink: beegfs-features/beegfs-csi-driver/csi-driver-tshoot.html
keywords: BeeGFS Features, CSI, Driver
summary: "Troubleshooting the BeeGFS CSI Driver Deployment."
---
= Troubleshooting the BeeGFS CSI Driver Deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../../media/


[.lead]
When troubleshooting issues with the BeeGFS CSI Driver deployment, ensure that:

* All prerequisites have been met, including the setup and configuration of the BeeGFS client.
* The BeeGFS CSI Driver has been deployed using the correct overlays.
* The deployment has been verified, and any errors—such as node taints or swap being enabled—have been addressed.
* Example applications have been deployed and validated to confirm functionality.


== Kubernetes setup - Common Error Scenarios 

Example error when attempting to retrieve all currently running pods on the node:

[source,console]   
----
kubectl get pods
----
.Output Showing an Error:
----
root@node@1:~# kubectl get pods 
E0829 14:30:28.644318 5617 memcache.go:265)] "Unhandled Error" err="couldn't get current server API group list: Get \"https://XX.YYY.ZZ.CC:644 
3: connect: connection refused" 
E0829 14:30:28.645853 5617 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://XX.YYY.ZZ.CC:644 
3: connect: connection refused" 
E0829 14:30:28.647177 5617 memcache.go:265) "Unhandled Error" err="couldn't get current server API group list: Get \"https://XX.YYY.ZZ.CC:644 
3: connect: connection refuse: 
E0829 14:30:28.648571 5617 memcache.go:265) "Unhandled Error" err="couldn't get current server API group list: Get \"https://XX.YYY.ZZ.CC:644 
3: connect: connection refused" 
E0829 14:30:28.650161 5617 memcache.go:265) "Unhandled Error" err="couldn't get current server API group list: Get \"https://XX.YYY.ZZ.CC:644 
3: connect: connection refused" 
 The connection to the server XX.YYY.ZZ.CC:6443 was refused - did you specify the right host or port? 
----

There are several key areas to investigate when addressing issues like these. We recommend reviewing them in the following order:

1. *Error in containerd*
+
Check the status of the containerd daemon:
+
[source,console]
----
systemctl status containerd
----
+
Expected Output:
+
----
root@node01:/home/user_id/beegfs-csi-driver# systemctl status containerd 
o containerd.service - containerd container runtime 
     Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled) 
     Active: inactive (dead) 
     Docs: https://containerd.io 
----
+
If the daemon is not running, restart it:
+
[source,console]
----
systemctl restart containerd
----
+
Expected Output:
+
----
root@node01:/home/user_id/beegfs-csi-driver# systemctl status containerd 
o containerd.service - containerd container runtime 
     Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled) 
     Active: inactive (dead) 
     Docs: https://containerd.io 
root@node01:/home/user_id/beegfs-csi-driver# systemctl start containerd  
root@node01:/home/user_id/beegfs-csi-driver# systemctl status containerd 
● containerd.service - containerd container runtime 
     Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled) 
     Active: active (running) since Mon 2025-10-13 11:55:05 CDT; 2s ago 
     Docs: https://containerd.io 
     Process: 2144996 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS) 
     Main PID: 2144997 (containerd) 
     Tasks: 382 
     Memory: 1.0G 
     CGroup: /system.slice/containerd.service 
----

[start=2]
. *Error in kubelet*
+
Check the status of the kubelet service: 
+
[source,console]
----
systemctl status kubelet
----
+
Expected Output:
+
----
root@node01:/home/user_id/beegfs-csi-driver# systemctl status kubelet 
o kubelet.service - kubelet: The Kubernetes Node Agent 
    Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled) 
    Drop-In: /usr/lib/systemd/system/kubelet.service.d 
             └─10-kubeadm.conf 
    Active: activating (auto-restart) (Result: exit-code) since Fri 2025-08-29 14:34:25 CDT; 6s ago 
      Docs: https://kubernetes.io/docs/ 
     Process: 6636 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG ARGS $KUBELET CONFIG ARGS $KUBELET KUBEADM ARGS
     $KUBELET_EXTRA ARGS (code=exited, status=1/FAILURE) 
     Main PID: 6636 (code=exited, status=1/FAILURE) 
----
+
If the service is not running, restart it:
+
[source,console]
----
systemctl restart kubelet
----
+
If issue persists, check the syslog for errors:
+
[source,console]
----
tail -f /var/log/syslog | grep kubelet   
----
+
*Swap Issue*
+
If you encounter errors related to “swap,” disable swap and restart the kubelet.
+
NOTE: For the swapoff command shown below, it’s best to type it manually rather than copy it from here. Copying may cause issues if the hyphen changes from a standard ASCII hyphen-minus (-) to a Unicode en dash (–).
+
[source,console]
----
swapoff -a
----
+
[source,console]
----
systemctl restart kubelet
----
+
Expected Output:
+
----
root@node01:/home/user_id/beegfs-csi-driver# systemctl status kubelet 
● kubelet.service - kubelet: The Kubernetes Node Agent 
    Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled) 
    Drop-In: /usr/lib/systemd/system/kubelet.service.d 
             └─10-kubeadm.conf 
     Active: active (running) since Tue 2025-10-07 18:11:05 CDT; 5 days ago 
       Docs: https://kubernetes.io/docs/ 
   Main PID: 1302401 (kubelet) 
      Tasks: 58 (limit: 231379) 
     Memory: 63.0M 
     CGroup: /system.slice/kubelet.service 
             └─1302401 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml conta>
----
+
NOTE: Swap is usually enabled by default during the operating system installation and is listed in /etc/fstab. Kubernetes does not support running with swap enabled. 

[start=3]
. *Troubleshooting BeeGFS Client and Helperd Configuration*
+
Review the configuration in /etc/beegfs/beegfs-client.conf. 
+
* If your BeeGFS file system requires connection authentication, ensure that the following flag is set to false: 
+
[source,console]
----
connAuthFileEnabled = false
----
+
NOTE: If the customer chooses to allow the BeeGFS file system to connect without authentication, the flag above should be set to true.
+
* Update the IP address for the management service in the sysMgmtdHost parameter. 
* Update the paths for connRDMAInterfacesFile and connInterfacesFile. These files specify the network interfaces used for storage or inter-node communication. For example:
+
[source,shell]
----
ibs1f0 
ibs1f1 
----
+
* Update the path for the connAuthFile parameter *if* authentication is enabled. 
+
Example configuration screenshot shown below:
+
----
connDisableAuthentication = false 
# BEGIN ANSIBLE NETAPP_ESERIES.HOST.UPDATE_CONF MANAGED BLOCK 
connClientPortUDP=8004  
connMaxInternodeNum=128  
connMaxConcurrentAttempts=4  
connRDMABufNum=36  
connRDMABufSize=65536  
tuneFileCacheType=native  
tuneFileCacheBufSize=2097152  
connFallbackExpirationSecs=90  
connCommRetrySecs=600  
sysSessionChecksEnabled=False connRDMAInterfacesFile=/etc/beegfs/XXX.X.XX.X_8004_connInterfaces.conf sysMountSanityCheckMS=11000  
connRDMAKeyType=dma  
sysMgmtdHost=XXX.X.XX.X  
connInterfacesFile=/etc/beegfs/XXX.X.XX.X_8004_connInterfaces.conf connAuthFile=/etc/beegfs/XXX.X.XX.X connAuthFile 
----
+
* Review the configuration in /etc/beegfs/beegfs-helperd.conf.
+
** If your BeeGFS file system uses connection authentication, ensure that the following flag is also set to false in the helperd.conf file: 
+
[source,console]
----
connDisableAuthentication = false 
----
+
NOTE: If the customer chooses to allow the BeeGFS file system to connect without authentication, set the flag above to true.
+
Example configuration shown below:
+
----
# --- Section 1: [Settings] ---  
# 
connAuthFile 			= /etc/beegfs/XXX.X.XX.X_connAuthFile 
connDisableAuthentication 	= false  

connHelperdPortTCP 		= 8006  
connPortShift 			= 0 

logNoDate 				= false  
logNumLines 			= 50000  
logNumRotatedFiles 		= 5  
logStdFile 			= /var/log/beegfs-client.log  
runDaemonized 			= true  
tuneNumWorkers 			= 2 
----

[start=4]
. *Troubleshooting Airgapped Kubernetes Deployment*

* If your air-gapped environment does not have a Docker Hub mirror, pull the required images from a machine with internet access and save them as tar files.  

* List of docker images can be found in the yaml files in `deploy/k8s/overlays/default/kustomization.yaml`
+
[source,console]
----
# images section is used to transform the image name specify the specific image to use in the deployment 
# or other scenarios where custom containers names are used. You can adjust the registry and/or location within 
# a registry with the newName field. You can change the tag being used with the NewTag field. You can also 
# use an image digest with the digest field. 
# See https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_imagetagtransformer_ 
for more information on how to use this section. 
#images: 
name: ghcr.io/thinkparq/beegfs-csi-driver newTag: v1.5.0 
newTag: v1.5.0 
digest: sha256:9027762e2ae434aa52a071a484b0a7e26018c64d0fb884f7f8cff0af970c4eb8 
name: k8s.gcr.io/sig-storage/csi-provisioner 
newName: 
newTag: 
name: k8s.gcr.io/sig-storage/csi-resizer newName: 
newTag: 
name: k8s.gcr.io/sig-storage/livenessprobe 
newName: 
newTag: 
name: k8s.gcr.io/sig-storage/csi-node-driver-registrar 
newName: 
newTag: 
----
+
* On a machine with internet access, save the images as tar files using the following command:
+
[source,shell]
----
docker pull docker.io/netapp/beegfs-csi-driver 
----
+
[source,shell]
----
docker save docker.io/netapp/beegfs-csi-driver > beegfs-csi-driver.tar
----
+
* Copy the tar file to the airgapped kubernetes node and load them as shown below: 
+
[source,shell]
----
docker load < beegfs-csi-driver.tar.gz
----
+
Once the images are available, copy `deploy/k8s/overlays/default` to `deploy/k8s/overlays/my-overlay` and update the image references to point to the locally available images. Adjust the images[].newTag fields as needed to match the images on the Kubernetes nodes or to reference your internal registry.

[start=5]
. *Troubleshooting BeeGFS Controller issues*
+
After deploying the overlays, you may see some resources with a PENDING status in the output of kubectl get all.
+
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl get all -n beegfs-csi 
NAME                          READY   STATUS    RESTARTS   AGE 
pod/csi-beegfs-controller-0   0/3     Pending   0          59s 
----
+
If the status appears as shown above, proceed to inspect the created pods using the describe command.
+
[source,shell]
----
kubectl describe pod csi-beegfs-controller-0 -n beegfs-csi 
----
+
If you encounter errors related to "untolerated taint" (visible in the output of kubectl describe) as below: 
+
----
Events: 
  Type     Reason            Age   From               Message 
  ----     ------            ----  ----               ------- 
  Warning  FailedScheduling  84s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling. 
----
+
Remove the taint from the node using the following command:
+
[source,shell]
----
kubectl taint nodes node01 node-role.kubernetes.io/control-plane:NoSchedule-
----
+
Expected Output:
+
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl taint nodes node01 node-role.kubernetes.io/control-plane:NoSchedule-  
error: taint "node-role.kubernetes.io/control-plane:NoSchedule" not found 
----
+
After removing the taint, reapply the overlays. This should resolve the issue:
+
[source,shell]
----
kubectl apply -k deploy/k8s/overlays/default 
----


[start=6]
. *Downloading the images and saving them locally*
+
NOTE: These images are first pulled from Docker and then saved locally as tar files.
+
These are the commands used: 
+
[source,shell]
----
docker pull ghcr.io/thinkparq/beegfs-csi-driver:v1.7.0 
docker pull registry.k8s.io/sig-storage/csi-provisioner:v3.5.0 
docker pull registry.k8s.io/sig-storage/csi-resizer:v1.11.1 
docker pull registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0 
docker pull registry.k8s.io/sig-storage/livenessprobe:v2.10.0 
----
+
These are the commands used to save the docker images as tar files: 
+
[source,shell]
----
docker save ghcr.io/thinkparq/beegfs-csi-driver:v1.7.0 -o beegfs-csi-driver_v1.7.0.tar 
docker save registry.k8s.io/sig-storage/csi-provisioner:v3.5.0 -o csi-provisioner_v3.5.0.tar 
docker save registry.k8s.io/sig-storage/csi-resizer:v1.11.1 -o csi-resizer_v1.11.1.tar 
docker save registry.k8s.io/sig-storage/livenessprobe:v2.10.0 -o livenessprobe_v2.10.0.tar 
docker save registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0 -o csi-node-driver-registrar_v2.8.0.tar 
----


